apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: web-app
spec:
  containers:
  - name: nginx-container
    image: {{ .Values.container.image}}
    ports:
    - containerPort: 80