pipeline {
    agent any

    environment {
        SERVICE_NAME = 'tz-service'
        NAMESPACE = 'default'
    }

    stages {

        stage('Clone halm-chart'){
            steps{
                git 'https://github.com/Cheeelick/TZ.git'
            }
        }
        
        stage('Install halm'){
            steps{
                script{
                    sh 'curl -LO https://get.helm.sh/helm-v3.7.0-linux-amd64.tar.gz'
                    sh 'tar -zxvf helm-v3.7.0-linux-amd64.tar.gz'
                    sh 'mv linux-amd64/helm /usr/local/bin/helm'
                }
            }
        }

        stage('Install halm-chart repo'){
            steps{
                script{
                    sh 'helm install web-app ./TZ/chart_nginx'
                }
            }
        }

        stage('Get ClusterIP') {
            steps {
                script {
                    CLUSTER_IP = sh(script: "kubectl get svc ${SERVICE_NAME} -n ${NAMESPACE} -o jsonpath='{.spec.clusterIP}'", returnStdout: true).trim()
                    echo "ClusterIP is ${CLUSTER_IP}"
                }
            }
        }

        stage('Use ClusterIP') {
            steps {
                script {
                    sh "curl http://${CLUSTER_IP}:32080"
                }
            }
        }
    }
}
